-- FASCAL CX-Channel database schema
-- Combined from the Prisma migrations (init + rma_status + ip_courier_name + ip_repaired_by)
-- Load with:  mysql -h 127.0.0.1 -P 3307 -u cx_user -p cx_channel < schema.sql

CREATE TABLE `users` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `first_name` VARCHAR(191) NULL,
    `last_name` VARCHAR(191) NULL,
    `username` VARCHAR(191) NOT NULL,
    `email` VARCHAR(191) NULL,
    `password` VARCHAR(191) NOT NULL,
    `role` VARCHAR(191) NOT NULL,
    `department` VARCHAR(191) NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    UNIQUE INDEX `users_username_key`(`username`),
    UNIQUE INDEX `users_email_key`(`email`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `requests` (
    `id` VARCHAR(191) NOT NULL,
    `rma_number` VARCHAR(191) NULL DEFAULT '',
    `rma_status` VARCHAR(191) NOT NULL DEFAULT 'RMA Not Received',
    `rma_issued_at` VARCHAR(191) NULL DEFAULT '',
    `pending_for_customer` VARCHAR(191) NOT NULL DEFAULT '',
    `pending_for_fastech` VARCHAR(191) NOT NULL DEFAULT '',
    `pending_for_oem` VARCHAR(191) NOT NULL DEFAULT '',
    `custom_status` VARCHAR(191) NOT NULL DEFAULT '',
    `approval_status` VARCHAR(191) NOT NULL DEFAULT '',
    `customer_mail_status` VARCHAR(191) NOT NULL DEFAULT '',
    `disapproval_reason` VARCHAR(191) NOT NULL DEFAULT '',
    `oem` VARCHAR(191) NOT NULL,
    `service_type` VARCHAR(191) NOT NULL,
    `product` VARCHAR(191) NOT NULL,
    `description` VARCHAR(191) NOT NULL DEFAULT '',
    `name` VARCHAR(191) NOT NULL,
    `email` VARCHAR(191) NOT NULL,
    `phone` VARCHAR(191) NOT NULL DEFAULT '',
    `company` VARCHAR(191) NOT NULL DEFAULT '',
    `designation` VARCHAR(191) NOT NULL DEFAULT '',
    `location` VARCHAR(191) NOT NULL DEFAULT '',
    `po_number` VARCHAR(191) NOT NULL DEFAULT '',
    `po_date` VARCHAR(191) NOT NULL DEFAULT '',
    `serial_single` VARCHAR(191) NOT NULL DEFAULT '',
    `serial_base_unit` VARCHAR(191) NOT NULL DEFAULT '',
    `serial_rf_cable` VARCHAR(191) NOT NULL DEFAULT '',
    `serial_antenna` VARCHAR(191) NOT NULL DEFAULT '',
    `billing_address` VARCHAR(191) NOT NULL DEFAULT '',
    `return_address` VARCHAR(191) NOT NULL DEFAULT '',
    `cal_certificate_address` VARCHAR(191) NOT NULL DEFAULT '',
    `additional_info` VARCHAR(191) NOT NULL DEFAULT '',
    `status` VARCHAR(191) NOT NULL DEFAULT 'fresh',
    `customer_feedback` VARCHAR(191) NOT NULL DEFAULT '',
    `internal_note` VARCHAR(191) NOT NULL DEFAULT '',
    `created_at` VARCHAR(191) NOT NULL,
    `updated_at` VARCHAR(191) NOT NULL,
    `ip_admin_note` VARCHAR(191) NOT NULL DEFAULT '',
    `ip_received_date` VARCHAR(191) NOT NULL DEFAULT '',
    `ip_date_of_investigation` VARCHAR(191) NOT NULL DEFAULT '',
    `ip_warranty` VARCHAR(191) NOT NULL DEFAULT '',
    `ip_investigation_details` VARCHAR(191) NOT NULL DEFAULT '',
    `ip_repair_details` VARCHAR(191) NOT NULL DEFAULT '',
    `ip_repaired_by` VARCHAR(191) NOT NULL DEFAULT '',
    `ip_estimate_date` VARCHAR(191) NOT NULL DEFAULT '',
    `ip_estimate_number` VARCHAR(191) NOT NULL DEFAULT '',
    `ip_estimate_amount` VARCHAR(191) NOT NULL DEFAULT '',
    `ip_po_no_and_date` VARCHAR(191) NOT NULL DEFAULT '',
    `ip_po_received_date` VARCHAR(191) NOT NULL DEFAULT '',
    `ip_oem_rma_no` VARCHAR(191) NOT NULL DEFAULT '',
    `ip_date_of_sent` VARCHAR(191) NOT NULL DEFAULT '',
    `ip_platform_module` VARCHAR(191) NOT NULL DEFAULT '',
    `ip_oem_quotation` VARCHAR(191) NOT NULL DEFAULT '',
    `ip_date_of_receiving_from_oem` VARCHAR(191) NOT NULL DEFAULT '',
    `ip_dc_no_and_date` VARCHAR(191) NOT NULL DEFAULT '',
    `ip_dispatched_date` VARCHAR(191) NOT NULL DEFAULT '',
    `ip_lr_no` VARCHAR(191) NOT NULL DEFAULT '',
    `ip_reason_for_waiting` VARCHAR(191) NOT NULL DEFAULT '',
    `ip_delivered_date` VARCHAR(191) NOT NULL DEFAULT '',
    `ip_ack_date_from_wh` VARCHAR(191) NOT NULL DEFAULT '',
    `ip_courier_name` VARCHAR(191) NOT NULL DEFAULT '',
    `ip_remark` VARCHAR(191) NOT NULL DEFAULT '',
    `ip_company_name` VARCHAR(191) NOT NULL DEFAULT '',
    `ip_location` VARCHAR(191) NOT NULL DEFAULT '',
    `ip_module_serial_number` VARCHAR(191) NOT NULL DEFAULT '',
    `ip_support_request` VARCHAR(191) NOT NULL DEFAULT '',
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `request_images` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `request_id` VARCHAR(191) NOT NULL,
    `original_name` VARCHAR(191) NOT NULL,
    `file_name` VARCHAR(191) NOT NULL,
    `path` VARCHAR(191) NOT NULL,
    `mime_type` VARCHAR(191) NOT NULL,
    `size` INTEGER NOT NULL,
    PRIMARY KEY (`id`),
    CONSTRAINT `request_images_request_id_fkey` FOREIGN KEY (`request_id`) REFERENCES `requests`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `support` (
    `id` VARCHAR(191) NOT NULL,
    `rma_number` VARCHAR(191) NOT NULL DEFAULT '',
    `subject` VARCHAR(191) NOT NULL DEFAULT '',
    `priority` VARCHAR(191) NOT NULL DEFAULT 'Medium',
    `oem` VARCHAR(191) NOT NULL,
    `service_type` VARCHAR(191) NOT NULL DEFAULT 'Support',
    `product` VARCHAR(191) NOT NULL,
    `description` VARCHAR(191) NOT NULL DEFAULT '',
    `name` VARCHAR(191) NOT NULL,
    `email` VARCHAR(191) NOT NULL,
    `phone` VARCHAR(191) NOT NULL DEFAULT '',
    `company` VARCHAR(191) NOT NULL DEFAULT '',
    `designation` VARCHAR(191) NOT NULL DEFAULT '',
    `location` VARCHAR(191) NOT NULL DEFAULT '',
    `software_version` VARCHAR(191) NOT NULL DEFAULT '',
    `serial_single` VARCHAR(191) NOT NULL DEFAULT '',
    `serial_base_unit` VARCHAR(191) NOT NULL DEFAULT '',
    `serial_rf_cable` VARCHAR(191) NOT NULL DEFAULT '',
    `serial_antenna` VARCHAR(191) NOT NULL DEFAULT '',
    `billing_address` VARCHAR(191) NOT NULL DEFAULT '',
    `return_address` VARCHAR(191) NOT NULL DEFAULT '',
    `cal_certificate_address` VARCHAR(191) NOT NULL DEFAULT '',
    `additional_info` VARCHAR(191) NOT NULL DEFAULT '',
    `status` VARCHAR(191) NOT NULL DEFAULT 'Open',
    `assigned_team` VARCHAR(191) NOT NULL DEFAULT '',
    `assigned_name` VARCHAR(191) NOT NULL DEFAULT '',
    `approval_status` VARCHAR(191) NOT NULL DEFAULT '',
    `customer_mail_status` VARCHAR(191) NOT NULL DEFAULT '',
    `disapproval_reason` VARCHAR(191) NOT NULL DEFAULT '',
    `internal_note` VARCHAR(191) NOT NULL DEFAULT '',
    `customer_feedback` VARCHAR(191) NOT NULL DEFAULT '',
    `pending_for_customer` VARCHAR(191) NOT NULL DEFAULT '',
    `pending_for_fastech` VARCHAR(191) NOT NULL DEFAULT '',
    `pending_for_oem` VARCHAR(191) NOT NULL DEFAULT '',
    `created_at` VARCHAR(191) NOT NULL,
    `updated_at` VARCHAR(191) NOT NULL,
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `support_images` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `support_id` VARCHAR(191) NOT NULL,
    `original_name` VARCHAR(191) NOT NULL,
    `file_name` VARCHAR(191) NOT NULL,
    `path` VARCHAR(191) NOT NULL,
    `mime_type` VARCHAR(191) NOT NULL,
    `size` INTEGER NOT NULL,
    PRIMARY KEY (`id`),
    CONSTRAINT `support_images_support_id_fkey` FOREIGN KEY (`support_id`) REFERENCES `support`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;